version: '3.5'

services:
  galaxy:
    container_name: galaxy
    restart: always
    image: registry.gitlab.ics.muni.cz:443/europdx/pdx-pipelines/galaxy-docker
    ports:
      - 8080:8080

    volumes:
      - /your/import/dir:/import
      - /your/dir/to/store/reference/files:/galaxy/reference-data/
