version: '3.5'

services:
  galaxy:
    container_name: galaxy
    restart: always
    image: edirex/galaxy:latest
    ports:
      - 8080:8080

    volumes:
      - ../Sample_data:/import
      - ./galaxy_instance:/galaxy/reference-data/
